### ISSUE TITLE
PHP 8.1 Minor Version

### ISSUE THREAD

**Issue by Miundaugs** [chialab/docker-php#123]
Hi, i'm using your package and it works great. Now i have issue where prod version is 8.1.29 and in local environment i have 8.1.6. My dockerfile starts like this "FROM chialab/php:8.1-fpm" and when i run "docker compose build --no-cahce" my containers rebuild, but i still getting same PHP version 8.1.6. Is it possible to upgrade this package so i could get PHP 8.1.29 ?

**Comment by fquffio** [comment]
Hi @Miundaugs! I just tried to run this command from my local machine: `docker run --rm -it chialab/php:8.1-fpm php --version`

I didn't have the image locally, so Docker downloaded the latest available image for that tag, and the PHP version that has been written to output is 8.1.29.

I assume you have a very old version of the image cached locally. Could you please try to run `docker compose build --no-cache --pull` (add `--pull` to the command you're using) and see if the latest image is correctly being used?

**Comment by Miundaugs** [comment]
Thank you @fquffio . It did worked and pulled new image. So `--no-cache` tag is for containers and `--pull` is for image itself?

**Comment by le0m** [comment]
Yes, pretty much: the `--no-cache` flag is about the [build cache](https://docs.docker.com/build/cache/), the `--pull` flag is to tell docker to actually compare the hash of your local image with the one available online (on DockerHub or other registry) and pull it if they're different.

Your prod has the latest one because you likely built it in CI (or on another machine), which didn't have the image locally and automatically pulled the new one.
