### ISSUE TITLE
Can't pull chialab/php-dev:7.2

### ISSUE THREAD

**Issue by fishnux** [Chialab/docker-php#25]
```
$ docker pull chialab/php-dev:7.2
Error response from daemon: manifest for chialab/php-dev:7.2 not found
```
Is anyone experiencing the same issue?

**Comment by fquffio** [comment]
Hey @fishnux ! Thanks for your interest in the project.

I'm afraid that `chialab/php-dev` for 7.2 series aren't available yet. Pull request #22 introduced images for PHP 7.2, but at the time XDebug wasn't available on PECL yet, so dev images were skipped. At the time of this writing, [XDebug for PHP 7.2 is only available as a beta release](https://pecl.php.net/package/xdebug), but I guess it's fine anyways for most users.

I'm on it! I just pushed a branch with the images you need… if TravisCI says everything is ok I'll open a PR, so that `chialab/php-dev:7.2` image will hopefully become available tomorrow. If you're in a hurry, you might checkout that branch and build the image yourself (`make -C dev build VERSION=7.2`).

**Comment by fishnux** [comment]
Thank you @fquffio !
