### ISSUE TITLE
Upgrade to Composer 2

### ISSUE THREAD

**Issue by le0m** [chialab/docker-php#73]
Composer 2 was released last week, this issue is for discussion about its adoption. See [here](https://github.com/composer/composer/blob/master/UPGRADE-2.0.md) for Composer 2 upgrade guide and possible breaking changes.

Current proposals (see https://github.com/chialab/docker-php/issues/72#issuecomment-719902517):
1. have separate images for Composer 1 and 2
1. install both as `composer1` and `composer2`, and create a `composer` symlink to the latter

Either way, builds are currently failing because `hirak/prestissimo` is not compatible with composer 2, nor it is needed with it.

**Comment by pazion** [comment]
I think seperate builds is a bit overkill.
Option 2 with symlinks sounds good.

**Comment by fquffio** [comment]
Ok, I've started working on this. Turns out having both `composer1` and `composer2` is a bit of a mess, as there is no obvious way to have them point to separate `$COMPOSER_HOME` directories. 😶 At least, I couldn't find any easy solution that didn't involve wrapping the Composer executable with some invoking.

This wouldn't be a problem if we didn't ship Composer 1 with `hirak/prestissimo` plugin already installed out of the box. This causes Composer 2 to try to load that plugin as well, and raise a non-fatal warning.

The "cleanest" solution I came up with was to wrap a custom executable around Composer 1 which sets the `COMPOSER_HOME` environment variable to a different value (`COMPOSER_HOME=$COMPOSER1_HOME`), and passes everything else down to the original Phar archive:

```dockerfile
# Install Composer 1 and 2. Expose `composer` as a symlink to `composer2`. Install `hirak/prestissimo` for Composer 1.
ENV PATH=$PATH:/root/composer2/vendor/bin:/root/composer1/vendor/bin \
  COMPOSER_ALLOW_SUPERUSER=1 \
  COMPOSER_HOME=/root/composer2 \
  COMPOSER1_HOME=/root/composer1
RUN cd /opt \
  && curl -sSL https://getcomposer.org/installer > composer-setup.php \
  && curl -sSL https://composer.github.io/installer.sha384sum > composer-setup.sha384sum \
  && sha384sum --check composer-setup.sha384sum \
  && php composer-setup.php --install-dir=/usr/local/bin --filename=.composer1 --1 \
  && php composer-setup.php --install-dir=/usr/local/bin --filename=composer2 --2 \
  && ln -s /usr/local/bin/composer2 /usr/local/bin/composer \
  && printf "#!/bin/sh\nCOMPOSER_HOME=\$COMPOSER1_HOME\nexec /usr/local/bin/.composer1 \$@" > /usr/local/bin/composer1 \
  && chmod 755 /usr/local/bin/composer1 \
  && composer1 global require hirak/prestissimo
```

Not actually something I would be proud of in 10 years from now, but sorta works. What do you think?

**Comment by le0m** [comment]
LGTM
The only problem I see with this solution is that users of this image could get an error if their application is not compatible with Composer 2. We could add a note in the README about `composer1`/`composer2` differentiation.

**Comment by fquffio** [comment]
Yep, but that's nice to add in any case, even if we would proceed with separate builds, as they would need to change the base image they build upon, and choose the one with Composer 1 instead.

**Comment by le0m** [comment]
We could've kept the current tags for Composer 1 images and introduce new tags for Composer 2, but that would probably have required more work and the solution you submitted makes more sense to me. I'll add a note in the README.
