### ISSUE TITLE
php:5.6-apache not serving files anymore

### ISSUE THREAD

**Issue by n2o** [chialab/docker-php#89]
Hello,

thanks for your work in this project! With your last release the behavior of the image changed, which is why it is currently not usable, but I think we can fix this :-) With the latest image, the container does not serve the PHP files, but starts in an interactive mode on the console:

```
web_1    | Interactive shell
web_1    | 
web_1    | php > Interactive shell
web_1    | 
web_1    | php > Interactive shell
web_1    | 
web_1    | php > ⏎                
```

This repeats until the container dies.

I start the container and mount the files to `/var/www/html`

```
volumes:
  - ./html:/var/www/html
```

Thanks for your help!

**Comment by fquffio** [comment]
Hi @n2o ! Sorry for the inconvenience.
I just tried and `docker run --rm -it chialab/php:5.6-apache` currently works for me, as it starts an Apache server with `apache2 -D FOREGROUND`.

However, yesterday I pushed a refactor that caused all images to be built upon `php:latest`, which has PHP 8.0.11 and no Apache server by default. We solved it in #88 and should have been fixed by yesterday at around 5pm UTC… can you check again if the problem still persist? Remember to `docker pull chialab/php:5.6-apache` first to ensure you use the latest built image…
